### ISSUE TITLE
Feature Request: Csharp implementation

### ISSUE THREAD

**Issue by s7uvx** [ar0551/Wasp#17]
Hi Andrea, would you consider progressively transitioning the Wasp plugin to Csharp, probably starting with the most heavy components (field based aggregation seems to be the worst offender)?

**Comment by ar0551** [comment]
I am sorry, but this is not planned for a series of reasons:
- The long term goal for Wasp is to support other platforms beyond Rhino/Grasshopper (e.g., Blender, Compas), so Python provides the cross-platform compatibility to do that.
- I favor the openness of Python components, where code is directly accessible and readable, over compiled plug-ins.
- I am a pretty crappy C# developer :)

**Comment by ar0551** [comment]
Wasp is open-source software, and I would definitely encourage anyone interested in porting Wasp to other platforms/languages, but that is not something I will do personally.

**Comment by s7uvx** [comment]
Thanks, I might give it a shot, but didn’t want to embark down that road if you’re already halfway through.Sent from my iPhoneOn 7 Apr 2024, at 4:17 am, Andrea Rossi ***@***.***> wrote:﻿
Wasp is open-source software, and I would definitely encourage anyone interested in porting Wasp to other platforms/languages, but that is not something I will do personally.
